DefaultContentLanguage = "en"
baseURL = "https://www2.podigee.com/"
defaultContentLanguageInSubdir = true
metaDataFormat = "yaml"
theme = "podigee"
[Languages.de]
title = "Podigee Podcast Hosting"
[Languages.en]
title = "Podigee Podcast Hosting"
[params]
analytics_key = "gBLJbe7dK7pkedcxKH2WM0yilNDxCZPN"
authors = "Podigee"
description = "Podigee is awesome"
keywords = ["podcast", "hosting", "publishing", "podigee", "transcription", "podcasting", "webplayer"]
login_link = "https://app.podigee.com/"
page_title = "Podigee Podcast Hosting"
register_link = "https://app.podigee.com/register"
