metaDataFormat = "yaml"
baseURL = "https://www.podigee.com/"
DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
theme = "podigee"

[params]
  page_title = "Podigee Podcast Hosting"
  description = "Podigee is awesome"
  authors = "Podigee"
  keywords = [
    "podcast",
    "hosting",
    "publishing",
    "podigee",
    "transcription",
    "podcasting",
    "webplayer"
  ]
  register_link = "https://app.podigee.com/register"
  login_link = "https://app.podigee.com/"
  analytics_key = "gBLJbe7dK7pkedcxKH2WM0yilNDxCZPN"

[Languages]
[Languages.en]
title = "Podigee Podcast Hosting"

[Languages.de]
title = "Podigee Podcast Hosting"
